spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bookdb
    username: postgres
    password: testpassword
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      format-sql: true
#      ddl-auto: create-drop

shell:
  output:
    errorMessage: Some error occured. Please, try once more
    notFoundMessage: Nothing was found
    defaultMessage: Ok