spring:
  data:
    mongodb:
      database: bookdb
      port: 27017
  shell:
    output:
      errorMessage: Some error occured. Please, try once more
      notFoundMessage: Nothing was found
      defaultMessage: Ok
migration:
  changelogPackage: ru.otus.spring.mongo_db_book_info_app.migration.changelog